spring:
  #Datasource configuration (database connection)
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:demodb
    username: ""
    password: ""
  #JPA-Hibernate configuration
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      ddl-auto: update
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: file:src/main/resources/templates/

